environment:
  repository_directory: $(APPVEYOR_BUILD_FOLDER)
  nuget_uri: https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  nuget_exe_path: $(repository_directory)\nuget.exe
  nuget_push_uri: https://www.myget.org/F/sped-mobi/api/v2/package
  myget_api_key: d3cb76e3-890c-4874-a882-267e518aee3d
  nupkg_artifact_path: $(repository_directory)\artifacts\packages\$(configuration)\Shipping\
  
init:
- cmd: >-
    @echo off

    cls

    echo APPVEYOR = $(APPVEYOR)

    echo APPVEYOR_API_URL = $(APPVEYOR_API_URL)

    echo APPVEYOR_ACCOUNT_NAME = $(APPVEYOR_ACCOUNT_NAME)

    echo APPVEYOR_PROJECT_ID = $(APPVEYOR_PROJECT_ID)

    echo APPVEYOR_PROJECT_NAME = $(APPVEYOR_PROJECT_NAME)

    echo APPVEYOR_PROJECT_SLUG = $(APPVEYOR_PROJECT_SLUG)

    echo APPVEYOR_BUILD_FOLDER = $(APPVEYOR_BUILD_FOLDER)

    echo APPVEYOR_BUILD_ID = $(APPVEYOR_BUILD_ID)

    echo APPVEYOR_BUILD_NUMBER = $(APPVEYOR_BUILD_NUMBER)

    echo APPVEYOR_BUILD_VERSION = $(APPVEYOR_BUILD_VERSION)

    echo APPVEYOR_BUILD_WORKER_IMAGE = $(APPVEYOR_BUILD_WORKER_IMAGE)

    echo APPVEYOR_PULL_REQUEST_NUMBER = $(APPVEYOR_PULL_REQUEST_NUMBER)

    echo APPVEYOR_PULL_REQUEST_TITLE = $(APPVEYOR_PULL_REQUEST_TITLE)

    echo APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME = $(APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME)

    echo APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH = $(APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH)

    echo APPVEYOR_PULL_REQUEST_HEAD_COMMIT = $(APPVEYOR_PULL_REQUEST_HEAD_COMMIT)

    echo APPVEYOR_JOB_ID = $(APPVEYOR_JOB_ID)

    echo APPVEYOR_JOB_NAME = $(APPVEYOR_JOB_NAME)

    echo APPVEYOR_JOB_NUMBER = $(APPVEYOR_JOB_NUMBER)

    echo APPVEYOR_REPO_PROVIDER = $(APPVEYOR_REPO_PROVIDER)

    echo APPVEYOR_REPO_SCM = $(APPVEYOR_REPO_SCM)

    echo APPVEYOR_REPO_NAME = $(APPVEYOR_REPO_NAME)

    echo APPVEYOR_REPO_BRANCH = $(APPVEYOR_REPO_BRANCH)

    echo APPVEYOR_REPO_TAG = $(APPVEYOR_REPO_TAG)

    echo APPVEYOR_REPO_TAG_NAME = $(APPVEYOR_REPO_TAG_NAME)

    echo APPVEYOR_REPO_COMMIT = $(APPVEYOR_REPO_COMMIT)

    echo APPVEYOR_REPO_COMMIT_AUTHOR = $(APPVEYOR_REPO_COMMIT_AUTHOR)

    echo APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL = $(APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL)

    echo APPVEYOR_REPO_COMMIT_TIMESTAMP = $(APPVEYOR_REPO_COMMIT_TIMESTAMP)

    echo APPVEYOR_REPO_COMMIT_MESSAGE = $(APPVEYOR_REPO_COMMIT_MESSAGE)

    echo APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED = $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)

    echo APPVEYOR_SCHEDULED_BUILD = $(APPVEYOR_SCHEDULED_BUILD)

    echo APPVEYOR_FORCED_BUILD = $(APPVEYOR_FORCED_BUILD)

    echo APPVEYOR_RE_BUILD = $(APPVEYOR_RE_BUILD)

    echo APPVEYOR_RE_RUN_INCOMPLETE = $(APPVEYOR_RE_RUN_INCOMPLETE)

    echo APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT = $(APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT)

    echo APPVEYOR_FILE_DOWNLOAD_TIMEOUT = $(APPVEYOR_FILE_DOWNLOAD_TIMEOUT)

    echo APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT = $(APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT)

    echo APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT = $(APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT)

    echo APPVEYOR_CACHE_SKIP_RESTORE = $(APPVEYOR_CACHE_SKIP_RESTORE)

    echo APPVEYOR_CACHE_SKIP_SAVE = $(APPVEYOR_CACHE_SKIP_SAVE)

    echo APPVEYOR_WAP_ARTIFACT_NAME = $(APPVEYOR_WAP_ARTIFACT_NAME)

    echo APPVEYOR_WAP_SKIP_ACLS = $(APPVEYOR_WAP_SKIP_ACLS)

    echo APPVEYOR_BUILD_WORKER_IMAGE = $(APPVEYOR_BUILD_WORKER_IMAGE)

    echo APPVEYOR_SKIP_FINALIZE_ON_EXIT = $(APPVEYOR_SKIP_FINALIZE_ON_EXIT)

    echo APPVEYOR_SAVE_CACHE_ON_ERROR = $(APPVEYOR_SAVE_CACHE_ON_ERROR)

    echo APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE = $(APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE)

    echo APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG = $(APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG)


version: 1.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- nuget restore
  
build_script:
- cmd: Release.cmd

deploy_script:
- cmd: Deploy.cmd
