version: 1.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

artifacts:
- path: artifacts/bin/**/*.dll
  name: Binary File

before_build:
- nuget restore
  
build_script:
- cmd: Release.cmd

deploy_script:
- cmd: Deploy.cmd
