version: 1.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- nuget restore

build_script:
- cmd: Release.cmd

deploy:
- provider: NuGet
  server: https://www.myget.org/F/sped-mobi/api/v2/package
  api_key:
    secure: IINWWcWt5v6l9MTThANW5/OTwK2y5xCdkjkYak2Zd681rCHaYxu9bwLzIdKM78G9
  skip_symbols: true
  on:
    branch: master
