// -----------------------------------------------------------------------
// <copyright file="AbstractIndentedCodeWriter.cs" company="Ollon, LLC">
//     Copyright (c) 2017 Ollon, LLC. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore.Design;

namespace Microsoft.EntityFrameworkCore.Design.Internal
{
    public abstract class AbstractIndentedCodeWriter
    {
        private readonly IndentedWriter _writer;

        protected AbstractIndentedCodeWriter(IStringBuilderProvider provider)
        {
            _writer = new IndentedWriter(provider.Builder);
            Provider = provider;
        }

        protected virtual IStringBuilderProvider Provider { get; }

        protected void PushIndent()
        {
            _writer.PushIndent();
        }

        protected void PopIndent()
        {
            _writer.PopIndent();
        }

        protected void Write(string value)
        {
            _writer.Write(value);
        }

        protected void WriteLine(string value)
        {
            _writer.WriteLine(value);
        }

        protected void WriteLine()
        {
            _writer.WriteLine();
        }

        protected void Clear()
        {
            Provider.Builder.Clear();
        }

        protected string GetText()
        {
            return Provider.Builder.ToString();
        }

        protected IDisposable OpenBlock()
        {
            return _writer.OpenBlock();
        }

        protected virtual void GenerateFileHeader()
        {
            WriteLine($"//------------------------------------------------------------------------------");
            WriteLine($"// <auto-generated>");
            WriteLine($"//     This code was generated by a tool.");
            WriteLine($"//     Runtime Version:4.0.30319.42000");
            WriteLine($"//");
            WriteLine($"//     Generation Time: {DateTime.Now.ToLongDateString()} @ {DateTime.Now.TimeOfDay}");
            WriteLine($"//");
            WriteLine($"//     Changes to this file may cause incorrect behavior and will be lost if");
            WriteLine($"//     the code is regenerated.");
            WriteLine($"// </auto-generated>");
            WriteLine($"//------------------------------------------------------------------------------");
            WriteLine($"//");

        }
    }
}
